name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t trial:v7 .

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: trialcicd.azurecr.io
          username: ${{ secrets.AZURE_CR_USERNAME }}
          password: ${{ secrets.AZURE_CR_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag trial:v7 trialcicd.azurecr.io/trial:v7
          docker push trialcicd.azurecr.io/trial:v7
---
on: [push]

name: Run Azure Login without subscription

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2              
        
      - name: Azure Login
        uses: Azure/login@v2.1.1  
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Run Azure PowerShell
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: trialgithubactions
          slot-name: production
          images: 'trialcicd.azurecr.io/trial:v7'
