name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t trial:v7 .

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: trialcicd.azurecr.io
          username: ${{ secrets.AZURE_CR_USERNAME }}
          password: ${{ secrets.AZURE_CR_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag trial:v7 trialcicd.azurecr.io/trial:v7
          docker push trialcicd.azurecr.io/trial:v7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: trialgithubactions
          slot-name: production
          #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'trialcicd.azurecr.io/trial:v7'
          File: .github/workflows/workflow.yml
